name: build-apk
on:
  workflow_dispatch:
  push: { branches: [ main ] }   # así también se ejecuta al hacer commit
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g eas-cli
      - name: Build debug APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build -p android --profile debug-apk --non-interactive --json > build.json
      - name: Download APK
        run: |
          sudo apt-get update && sudo apt-get install -y jq curl
          URL=$(jq -r '.artifacts.buildUrl // .[0].artifacts.buildUrl' build.json)
          mkdir -p dist && curl -L "$URL" -o dist/AmbiVision-debug.apk
      - uses: actions/upload-artifact@v4
        with:
          name: AmbiVision-debug-apk
          path: dist/AmbiVision-debug.apk
